apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "chart.name" . }}-network-policy
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chart.name" . }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingress.namespace }}
      ports:
        {{- range .Values.networkPolicy.ingress.ports }}
        - protocol: {{ .protocol | default "TCP" }}
          port: {{ .port }}
        {{- end }}
  egress:
    {{- if .Values.networkPolicy.egress.enabled }}
    - to:
        - ipBlock:
            cidr: {{ .Values.networkPolicy.egress.cidr }}
      ports:
        {{- range .Values.networkPolicy.egress.ports }}
        - protocol: {{ .protocol | default "TCP" }}
          port: {{ .port }}
        {{- end }}
    {{- end }}


