apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "chart.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "chart.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
